### ISSUE TITLE
fatal error: soc/cpu.h: No such file or directory

### ISSUE THREAD

**Issue by RepRapThailand** [phorton1/Arduino-esp32_cnc3018#3]
Hi,

c:\Users\xcu\OneDrive\Documents\Arduino\libraries\Arduino-libraries-FluidNC-master\src\StackTrace\debug_helpers.cpp:24:14: fatal error: soc/cpu.h: No such file or directory
   24 | #    include "soc/cpu.h"
      |              ^~~~~~~~~~~
compilation terminated.
Alternatives for soc/cpu.h: []
ResolveLibrary(soc/cpu.h)
  -> candidates: []

Compile with Arduino 2.3.6
How to solve?

Regards,
